apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost-pg
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'mattermost'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'
    chart: postgresql
    path: postgresql
    targetRevision: 16.4.16
    helm:
      values: |-
        nameOverride: postgresql
        fullnameOverride: postgresql
        global:
          defaultStorageClass: "openebs-lvmpv"
        primary:
          extendedConfiguration: |-
            max_connections = 300
            shared_buffers = 256MB
          resources:
            limits:
              memory: 850Mi
              cpu: 850m
            requests:
              memory: 700Mi
              cpu: 700m
          persistence:
            size: 10Gi
        auth:
          existingSecret: "mattermost-postgres-password"
          secretKeys:
            adminPasswordKey: postgresPassword
            replicationPasswordKey: replicationPassword
        extraDeploy:
          - apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: mattermost-postgres-password
            spec:
              secretStoreRef:
                name: aws-parameter-store
                kind: ClusterSecretStore
              refreshInterval: "1h"
              target:
                name: mattermost-postgres-password
                deletionPolicy: "Delete"
              dataFrom:
                - extract:
                    key: "/homelab/mattermost-postgres-password"
          - apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: db-credentials
            spec:
              refreshInterval: 1h
              secretStoreRef:
                kind: ClusterSecretStore
                name: aws-parameter-store
              target:
                name: db-credentials
                creationPolicy: Owner
                template:
                  data:
                    DB_CONNECTION_STRING: postgres://postgres:{{ `{{ .postgresPassword }}` }}@postgresql.mattermost.svc.cluster.local:5432/mattermost?sslmode=disable
              dataFrom:
                - extract:
                    key: "/homelab/mattermost-postgres-password"
