apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'n8n'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: '8gears.container-registry.com/library'
    chart: n8n
    path: n8n
    targetRevision: 1.0.7
    helm:
      values: |-
        nameOverride: n8n
        fullnameOverride: n8n
        image:
          tag: "1.97.1"
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          className: "nginx"
          hosts:
            - host: n8n.idena.wf
              paths:
                - "/"
          tls:
            - hosts:
                - n8n.idena.wf
              secretName: tls-wildcard-idena-wf
        main:
          persistence:
            enabled: true
            type: dynamic
            storageClass: "local-path"
            size: 5Gi
          extraEnv:
            N8N_EDITOR_BASE_URL:
              value: "https://n8n.idena.wf"
            WEBHOOK_URL:
              value: "https://n8n.idena.wf"
          extraVolumes:
            - name: share
              persistentVolumeClaim:
                claimName: filebrowser-rootdir
          extraVolumeMounts:
            - name: share
              mountPath: /n8n/share
