apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-test
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'postgres-test'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'
    chart: postgresql
    path: postgresql
    targetRevision: 16.4.16
    helm:
      values: |-
        nameOverride: postgresql
        fullnameOverride: postgresql
        global:
          security:
            allowInsecureImages: "true"
        postgresqlSharedPreloadLibraries: "pgaudit"
