apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rocketchat
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'rocketchat'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: https://rocketchat.github.io/helm-charts
    chart: rocketchat
    targetRevision: 6.25.0
    helm:
      values: |-
        nameOverride: rocketchat
        fullnameOverride: rocketchat
        mongodb:
          persistence:
            storageClass: "openebs-lvmpv"
        host: rocketchat.lewandowskim.com
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          tls:
          - hosts:
            - rocketchat.lewandowskim.com
            secretName: tls-wildcard-lewandowskim-com