apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rocketchat
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'rocketchat'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: https://rocketchat.github.io/helm-charts
    chart: rocketchat
    targetRevision: 6.23.2
    helm:
      values: |-
        nameOverride: rocketchat
        fullnameOverride: rocketchat
        existingMongodbSecret: ""
        mongodb:
          auth:
            passwords:
              - rocketchat
            rootPassword: rocketchatroot
          persistence:
            storageClass: "openebs-lvmpv"
            size: 10Gi
        persistence:
          enabled: true
          storageClass: "openebs-lvmpv"
          size: 10Gi
        host: rocketchat.lewandowskim.com
        ingress:
          enabled: true
          pathType: Prefix
          ingressClassName: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          path: /
          tls:
            - secretName: tls-wildcard-lewandowskim-com
              hosts:
                - rocketchat.lewandowskim.com