apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searxng
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'searxng'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: https://charts.searxng.org
    chart: searxng
    targetRevision: 1.0.1
    helm:
      values: |-
        nameOverride: searxng
        fullnameOverride: searxng
        env:
          INSTANCE_NAME: "searxng"
          SEARXNG_HOSTNAME: "searxng.searxng.svc.cluster.local:8080/"
          SEARXNG_BIND_ADDRESS: "0.0.0.0"
          SEARXNG_URL: "http://searxng.searxng.svc.cluster.local:8080/"
        persistence:
          config:
            enabled: true
            storageClass: openebs-lvmpv
            size: 10Gi
        # ingress:
        #   main:
        #     enabled: false
        #     primary: true
        #     annotations:
        #       nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        #       nginx.ingress.kubernetes.io/ssl-redirect: "true"
        #     ingressClassName: "nginx"
        #     hosts:
        #       -
        #         host: searxng.lewandowskim.com
        #         paths:
        #           -
        #             path: "/"
        #             pathType: Prefix
        #             service:
        #               name: searxng
        #               port: 8080
        #     tls:
        #       - hosts:
        #         - searxng.lewandowskim.com
        #       secretName: tls-wildcard-lewandowskim-com
        searxng:
          config:
            use_default_settings: true
            server:
              secret_key: a42423f21be10066e09c5359
            search:
              formats:
                - html
                - json
