apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-ssm-secret
            key: access-key
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-ssm-secret
            key: secret-access-key
            namespace: external-secrets