# apiVersion: amd.com/v1alpha1
# kind: DeviceConfig
# metadata:
#   name: gpu-operator
#   namespace: gpu-operator
#   labels:
#     {{- include "common.labels" . | nindent 4 }}
# spec:
#   driver:
#     enable: false
#   devicePlugin:
#     devicePluginImage: rocm/k8s-device-plugin:latest
#     nodeLabellerImage: rocm/k8s-device-plugin:labeller-latest
#   metricsExporter:
#     enable: true
#     serviceType: "ClusterIP"
#     image: rocm/device-metrics-exporter:v1.0.0
