apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crawl4ai.fullname" . }}
  labels:
    {{- include "crawl4ai.labels" . | nindent 4 }}
type: Opaque
data:
  CRAWL4AI_API_TOKEN: {{ randAlphaNum 32 | b64enc | quote }}
